### ISSUE TITLE
Additional character at the end of the string

### ISSUE THREAD

**Issue by YOKAICODE** [Jarusk/pass-rs#10]
On macOS Monterey, when generating a password, the "%" character is added at the end of the generated string.
Encoding set in the terminal UTF-8

**Comment by Jarusk** [comment]
Hey @YOKAICODE , I just released version [v0.3.3](https://github.com/Jarusk/pass-rs/releases/tag/v0.3.3). I don't have a Mac to test, so would you be able to confirm that the issue still impacts you?

I've added a test matrix and if this is still an issue I'll add better coverage and try to replicate the issue in tests. Thanks!

**Comment by jett06** [comment]
Works as expected with the new commit :)
```sh
$ pass-rs
eP98seS1iX68p7a260GYsZo7iWsk35mxX3kCaw
$ pass-rs -n
u0maIujnRIP5usSXK8V051frPPxlofO4HGO78V%
```

Thanks!

**Comment by Jarusk** [comment]
> Works as expected with the new commit :)
> 
> ```shell
> $ pass-rs
> eP98seS1iX68p7a260GYsZo7iWsk35mxX3kCaw
> $ pass-rs -n
> u0maIujnRIP5usSXK8V051frPPxlofO4HGO78V%
> ```
> 
> Thanks!

Glad to hear! Thanks for the help!
